# Generated by Django 5.2.1 on 2025-05-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleador', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('herramientas', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('completada', 'Completada')], default='activa', max_length=10)),
            ],
        ),
    ]
