# Generated by Django 5.1.3 on 2025-06-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_puesto', models.CharField(max_length=255)),
                ('rango_salarial', models.CharField(max_length=100)),
                ('experiencia_requerida', models.CharField(max_length=100)),
                ('modalidad_trabajo', models.CharField(max_length=100)),
                ('descripcion_puesto', models.TextField()),
                ('requisitos_calificaciones', models.TextField()),
                ('beneficios_compensaciones', models.TextField()),
                ('numero_postulantes', models.PositiveIntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ofertas/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('direccion_detalle', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('completada', 'Completada')], default='activa', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_limite', models.TimeField()),
                ('descripcion', models.TextField()),
                ('herramientas', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ofertas/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('direccion_detalle', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('completada', 'Completada')], default='activa', max_length=10)),
            ],
        ),
    ]
