# Generated by Django 5.1.3 on 2025-06-28 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempresa',
            name='empleador',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'empresa'}, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_empresa', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='ofertaempresa',
            name='id_comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.comunidad'),
        ),
        migrations.AddField(
            model_name='ofertaempresa',
            name='id_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento'),
        ),
        migrations.AddField(
            model_name='ofertaempresa',
            name='id_distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.distrito'),
        ),
        migrations.AddField(
            model_name='ofertaempresa',
            name='id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.provincia'),
        ),
        migrations.AddField(
            model_name='ofertausuario',
            name='empleador',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['ofrecer-trabajo', 'ambos']}, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_usuario', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='ofertausuario',
            name='id_comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.comunidad'),
        ),
        migrations.AddField(
            model_name='ofertausuario',
            name='id_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento'),
        ),
        migrations.AddField(
            model_name='ofertausuario',
            name='id_distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.distrito'),
        ),
        migrations.AddField(
            model_name='ofertausuario',
            name='id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.provincia'),
        ),
    ]
