# Generated by Django 5.2.1 on 2025-07-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0003_guardartrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempresa',
            name='numero_contacto',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para contacto', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ofertausuario',
            name='numero_contacto',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para contacto', max_length=15, null=True),
        ),
    ]
