# Generated by Django 5.2.1 on 2025-07-13 07:01

from django.db import migrations, models


def set_default_phone_number(apps, schema_editor):
    """Establece un número por defecto para los registros existentes sin número"""
    OfertaUsuario = apps.get_model('trabajos', 'OfertaUsuario')
    OfertaEmpresa = apps.get_model('trabajos', 'OfertaEmpresa')
    
    # Actualizar ofertas de usuario sin número
    OfertaUsuario.objects.filter(numero_contacto__isnull=True).update(numero_contacto='+51000000000')
    OfertaUsuario.objects.filter(numero_contacto='').update(numero_contacto='+51000000000')
    
    # Actualizar ofertas de empresa sin número
    OfertaEmpresa.objects.filter(numero_contacto__isnull=True).update(numero_contacto='+51000000000')
    OfertaEmpresa.objects.filter(numero_contacto='').update(numero_contacto='+51000000000')


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0004_ofertaempresa_numero_contacto_and_more'),
    ]

    operations = [
        # Primero establecer valores por defecto
        migrations.RunPython(set_default_phone_number),
        
        # Luego cambiar el campo a NOT NULL
        migrations.AlterField(
            model_name='ofertausuario',
            name='numero_contacto',
            field=models.CharField(help_text='Número de WhatsApp para contacto (obligatorio)', max_length=15),
        ),
        migrations.AlterField(
            model_name='ofertaempresa',
            name='numero_contacto',
            field=models.CharField(help_text='Número de WhatsApp para contacto (obligatorio)', max_length=15),
        ),
    ]
