# Generated by Django 5.2.1 on 2025-06-19 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriatrabajo',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoriatrabajo',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id_distrito', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distrito',
            },
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id_empleador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, null=True)),
                ('ruc', models.CharField(blank=True, null=True)),
                ('verificado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleador',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id_habilidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='Politicalegal',
            fields=[
                ('id_politica', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'politicalegal',
            },
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id_comunidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('id_distrito', models.ForeignKey(blank=True, db_column='id_distrito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.distrito')),
            ],
            options={
                'db_table': 'comunidad',
            },
        ),
        migrations.CreateModel(
            name='Ofertatrabajo',
            fields=[
                ('id_oferta', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('sueldo', models.FloatField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.categoriatrabajo')),
                ('id_empleador', models.ForeignKey(blank=True, db_column='id_empleador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleador')),
            ],
            options={
                'db_table': 'ofertatrabajo',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento')),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.AddField(
            model_name='distrito',
            name='id_provincia',
            field=models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.provincia'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('nombres', models.CharField(blank=True, null=True)),
                ('apellidos', models.CharField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('clave', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, null=True)),
                ('tipo_usuario', models.TextField(blank=True, null=True)),
                ('habilitado', models.BooleanField(blank=True, null=True)),
                ('id_comunidad', models.ForeignKey(blank=True, db_column='id_comunidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.comunidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='TrabajosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'trabajos_realizados',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('foto_url', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('redes_sociales', models.JSONField(blank=True, null=True)),
                ('categorias', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('id_comunidad', models.ForeignKey(blank=True, db_column='id_comunidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.comunidad')),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento')),
                ('id_distrito', models.ForeignKey(blank=True, db_column='id_distrito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.distrito')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_provincia', models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.provincia')),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id_postulacion', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.TextField(blank=True, null=True)),
                ('fecha_postulacion', models.DateField(blank=True, null=True)),
                ('id_oferta', models.ForeignKey(blank=True, db_column='id_oferta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ofertatrabajo')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'postulacion',
            },
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='Filtrotrabajoporzona',
            fields=[
                ('id_filtro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_comunidad', models.ForeignKey(blank=True, db_column='id_comunidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.comunidad')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'filtrotrabajoporzona',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('representante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.AddField(
            model_name='empleador',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('id_empleador', models.ForeignKey(blank=True, db_column='id_empleador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleador')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'denuncia',
            },
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='certificaciones/')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'certificacion',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_empleador', models.ForeignKey(blank=True, db_column='id_empleador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleador')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id_aviso', models.IntegerField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'avisos',
            },
        ),
        migrations.CreateModel(
            name='AntecedentePenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='penales/')),
                ('aprobado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'antecedente_penal',
            },
        ),
        migrations.CreateModel(
            name='ActividadReciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'actividad_reciente',
            },
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id_verificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'verificacion',
            },
        ),
        migrations.CreateModel(
            name='UsuarioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.categoriatrabajo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'usuario_categoria',
                'unique_together': {('id_usuario', 'id_categoria')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioHabilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_habilidad', models.ForeignKey(db_column='id_habilidad', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.habilidad')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'usuario_habilidad',
                'unique_together': {('id_usuario', 'id_habilidad')},
            },
        ),
    ]
