# Generated by Django 5.2.1 on 2025-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadReciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividad_reciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id_aviso', models.IntegerField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'avisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoriatrabajo',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoriatrabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id_comunidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comunidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'denuncia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disponibilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id_distrito', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id_empleador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, null=True)),
                ('ruc', models.CharField(blank=True, null=True)),
                ('verificado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filtrotrabajoporzona',
            fields=[
                ('id_filtro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'filtrotrabajoporzona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id_habilidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'habilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ofertatrabajo',
            fields=[
                ('id_oferta', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('sueldo', models.FloatField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ofertatrabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Politicalegal',
            fields=[
                ('id_politica', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'politicalegal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id_postulacion', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.TextField(blank=True, null=True)),
                ('fecha_postulacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'postulacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('redes_sociales', models.JSONField(blank=True, null=True)),
                ('categorias', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, null=True)),
                ('apellidos', models.CharField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('clave', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, null=True)),
                ('tipo_usuario', models.TextField(blank=True, null=True)),
                ('habilitado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCategoria',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_categoria', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioHabilidad',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_habilidad', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_habilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id_verificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verificacion',
                'managed': False,
            },
        ),
    ]
