# Generated by Django 5.2.1 on 2025-07-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='plan_actual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
