# Generated by Django 5.2.1 on 2025-06-08 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_profile_options_alter_usuario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_comunidad',
            field=models.ForeignKey(blank=True, db_column='id_comunidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.comunidad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_departamento',
            field=models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_distrito',
            field=models.ForeignKey(blank=True, db_column='id_distrito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.distrito'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_provincia',
            field=models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.provincia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_comunidad',
            field=models.ForeignKey(blank=True, db_column='id_comunidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.comunidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
