# Generated by Django 5.2.1 on 2025-06-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profile_id_comunidad_profile_id_departamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadreciente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='avisos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoriatrabajo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comunidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='denuncia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empleador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='filtrotrabajoporzona',
            options={},
        ),
        migrations.AlterModelOptions(
            name='habilidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ofertatrabajo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='politicalegal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postulacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuariocategoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuariohabilidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verificacion',
            options={},
        ),
    ]
