# Generated by Django 5.2.1 on 2025-06-10 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_iniciados', to='usuarios.usuario')),
                ('usuario_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_recibidos', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.IntegerField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('editado', models.BooleanField(default=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.DO_NOTHING, to='chats.chat')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'mensaje',
            },
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('usuario_1', 'usuario_2'), name='unique_chat_pair'),
        ),
    ]
