# Generated by Django 5.2.1 on 2025-06-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id_chat',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_mensaje',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
