# Generated by Django 5.1.3 on 2025-06-28 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='usuario_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_iniciados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='chat',
            name='usuario_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_recibidos', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='id_chat',
            field=models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.DO_NOTHING, to='chats.chat'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('usuario_1', 'usuario_2'), name='unique_chat_pair'),
        ),
    ]
